name: github_ssh_keygen
version: 1.0.6
description: A sample command-line application.
repository: https://github.com/relf108/github_ssh_keygen
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  dcli: ^1.7.1
dev_dependencies: 
  pedantic: ^1.10.0
  test: ^1.16.0
executables: 
  github_ssh_keygen: 
